config/routes.rb
Rails.application.routes.draw do
 

  resources :courses, :enrollments

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'    
  }


root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
    # Currently status is false 
    @status = false

    current_user_courses = current_user.courses.pluck(:id)

    #If user already enrolled in the courses then set the status as true
    if current_user_courses.include? @course.id
      @status = true
    end
  end

  # GET /courses/new
  # def new
  #   @course = Course.new
  # end

  # GET /courses/1/edit
  # def edit
  # end

  # POST /courses or /courses.json
  # def create
  #   @course = Course.new(course_params)

  #   respond_to do |format|
  #     if @course.save
  #       format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
  #       format.json { render :show, status: :created, location: @course }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @course.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /courses/1 or /courses/1.json
  # def update
  #   respond_to do |format|
  #     if @course.update(course_params)
  #       format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
  #       format.json { render :show, status: :ok, location: @course }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @course.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /courses/1 or /courses/1.json
  # def destroy
  #   @course.destroy

  #   respond_to do |format|
  #     format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.fetch(:course, {})
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
</div>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Show this course", @course %> |
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/index.html.erb
<!-- Course Page -->

<p style="color: green"><%= notice %></p>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
     <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Courses</li>
  </ol>
</nav>

<h1>List of Courses</h1>
    <% @courses.each do |course| %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= course.title %></h5>
        <p class="card-text"><%= course.description %></p>
        <a href="/courses/<%= course.id %>" class="btn btn-primary">View Course</a>
      </div>
    </div>

    <% end %>  

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/show.html.erb
<!-- Course Description & Enrollment Page -->

<p style="color: green"><%= notice %></p>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
     <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">
      <a href="/courses">Course</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page"><%= @course.title  %></li>
  </ol>
</nav>

<div class="card mb-3">
  <%= image_tag("adorable.jpg", :class => "card-img-top", :alt => "Card image cap")  %>
  <div class="card-body">
    <h5 class="card-title"><%= @course.title%></h5>
    <p class="card-text"><%= @course.description  %></p>
    <p class="card-text"><small class="text-muted">Course Status: <% @course.ongoing_status ? puts("Ongoing") : puts("Completed") %></small></p>


<!-- Enroll option -->


<% if @status == true %>
  <button type="button" class="btn btn-secondary">Enrolled</button>
<% else%> 
  <%= button_to "Enroll Class", enrollments_url(:course_id =>  @course.id) %>
<% end %> 
  </div>
</div>